name: "gha-node"

inputs:
  build:
    type: "boolean"
    required: false
    default: "true"

  format:
    type: "boolean"
    required: false
    default: "true"

  lint:
    type: "boolean"
    required: false
    default: "true"

  test:
    type: "boolean"
    required: false
    default: "true"

  working-directory:
    type: "string"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: "Setup Node.js."
      uses: "actions/setup-node@v4"
      with:
        node-version: "20.x"
        check-latest: true
        cache: "npm"
        cache-dependency-path: "${{ inputs.working-directory }}/package-lock.json"

    - name: "Install dependencies."
      shell: "bash"
      working-directory: "${{ inputs.working-directory }}"
      run: |
        npm ci

    - name: "Format."
      if: "${{ inputs.format == 'true' }}"
      shell: "bash"
      working-directory: "${{ inputs.working-directory }}"
      run: |
        npm run format:check

    - name: "Lint."
      if: "${{ inputs.lint == 'true' }}"
      shell: "bash"
      working-directory: "${{ inputs.working-directory }}"
      run: |
        npm run lint:check

    - name: "Run tests."
      if: "${{ inputs.test == 'true' }}"
      shell: "bash"
      working-directory: "${{ inputs.working-directory }}"
      run: |
        npm run test

    - name: "Build."
      if: "${{ inputs.build == 'true' }}"
      shell: "bash"
      working-directory: "${{ inputs.working-directory }}"
      run: |
        npm run build
